// codyze-console/src/main/webapp/src/components/ComponentsList.tsx
import { Link } from "react-router-dom";
import { ComponentJSON } from "@/types";

interface ComponentsListProps {
  components: ComponentJSON[];
}

/**
 * Component to display a list of components.
 * 
 * @param components List of components to display
 */
function ComponentsList({ components }: ComponentsListProps) {
  return (
    <>
      <h3 className="mb-2 text-lg font-medium">Components</h3>
      <ul className="divide-y divide-gray-200">
        {components.map((component) => (
          <li key={component.name} className="py-3">
            <Link
              to={`/component/${component.name}`}
              className="text-lg font-medium text-blue-600 hover:underline"
            >
              {component.name}
            </Link>
            <p className="mt-1 text-sm text-gray-600">
              {component.translationUnits.length} translation units
            </p>
          </li>
        ))}
      </ul>
    </>
  );
}

export default ComponentsList;

// codyze-console/src/main/webapp/src/lib/components/ComponentsList.svelte
<script lang="ts">
  import type { ComponentJSON } from '$lib/types';

  interface Props {
    components: ComponentJSON[];
  }

  let { components }: Props = $props();
</script>

<h3 class="mb-2 text-lg font-medium">Components</h3>
<ul class="divide-y divide-gray-200">
  {#each components as component (component.name)}
    <li class="py-3">
      <a
        href={`/component/${component.name}`}
        class="text-lg font-medium text-blue-600 hover:underline"
      >
        {component.name}
      </a>
      <p class="mt-1 text-sm text-gray-600">
        {component.translationUnits.length} translation units
      </p>
    </li>
  {/each}
</ul>
