// codyze-console/src/main/webapp/src/lib/components/navigation/Navbar.svelte
<nav class="bg-blue-600 text-white shadow-md">
  <div class="container mx-auto flex items-center justify-between px-4 py-3">
    <a href="/" class="text-xl font-bold">Codyze Console</a>
    <div>
      <a href="/" class="rounded px-3 py-2 hover:bg-blue-700"> Dashboard </a>
    </div>
  </div>
</nav>

// codyze-console/src/main/webapp/src/components/Navbar.tsx
// src/main/web/src/components/Navbar.tsx
import React from "react";
import { Link } from "react-router-dom";

const Navbar: React.FC = () => {
  return (
    <nav className="bg-blue-600 text-white shadow-md">
      <div className="container mx-auto flex items-center justify-between px-4 py-3">
        <Link to="/" className="text-xl font-bold">
          Codyze Console
        </Link>
        <div>
          <Link to="/" className="rounded px-3 py-2 hover:bg-blue-700">
            Dashboard
          </Link>
        </div>
      </div>
    </nav>
  );
};

export default Navbar;
