// codyze-server/src/main/webapp/src/components/ComponentsList.tsx
import React from 'react';
import { Link } from 'react-router-dom';
import { ComponentJSON } from '../types';

interface ComponentsListProps {
    components: ComponentJSON[];
}

const ComponentsList: React.FC<ComponentsListProps> = ({ components }) => {
    return (
        <>
            <h3 className="text-lg font-medium mb-2">Components</h3>
            <ul className="divide-y divide-gray-200">
                {components.map((component) => (
                    <li key={component.name} className="py-3">
                        <Link
                            to={`/component/${component.name}`}
                            className="text-blue-600 hover:underline text-lg font-medium"
                        >
                            {component.name}
                        </Link>
                        <p className="text-gray-600 text-sm mt-1">
                            {component.translationUnits.length} translation units
                        </p>
                    </li>
                ))}
            </ul>
        </>
    );
};

export default ComponentsList;

// codyze-console/src/main/webapp/src/lib/components/dashboard/ComponentsList.svelte
<script lang="ts">
  import type { ComponentJSON } from '$lib/types';

  interface Props {
    components: ComponentJSON[];
  }

  let { components }: Props = $props();
</script>

<h3 class="mb-2 text-lg font-medium">Components</h3>
<ul class="divide-y divide-gray-200">
  {#each components as component (component.name)}
    <li class="py-3">
      <a
        href={`/components/${component.name}`}
        class="text-lg font-medium text-blue-600 hover:underline"
      >
        {component.name}
      </a>
      <p class="mt-1 text-sm text-gray-600">
        {component.translationUnits.length} translation units
      </p>
    </li>
  {/each}
</ul>
