// codyze-server/src/main/resources/static/src/components/NodeTable.tsx
import React from 'react';
import { NodeInfo } from '../types';

interface NodeTableProps {
    nodes: NodeInfo[];
    highlightedNode: NodeInfo | null;
    setHighlightedNode: (node: NodeInfo | null) => void;
}

function NodeTable({ nodes, highlightedNode, setHighlightedNode }) {
    return (
        <div className="bg-white shadow-md rounded p-6">
            <h2 className="text-lg font-semibold mb-4">AST Nodes ({nodes.length})</h2>
            <div className="overflow-x-auto">
                <table className="min-w-full divide-y divide-gray-200">
                    <thead className="bg-gray-50">
                    <tr>
                        <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Type</th>
                        <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Name</th>
                        <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Location</th>
                        <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Code</th>
                    </tr>
                    </thead>
                    <tbody className="bg-white divide-y divide-gray-200">
                    {nodes.map((node) => (
                        <tr
                            key={node.id}
                            className={`${highlightedNode?.id === node.id ? 'bg-gray-100' : ''} hover:bg-gray-50 cursor-pointer`}
                            onMouseEnter={() => setHighlightedNode(node)}
                            onMouseLeave={() => setHighlightedNode(null)}
                        >
                            <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">{node.type}</td>
                            <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{node.name}</td>
                            <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                L{node.startLine}:C{node.startColumn} - L{node.endLine}:C{node.endColumn}
                            </td>
                            <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500 truncate max-w-xs">{node.code}</td>
                        </tr>
                    ))}
                    </tbody>
                </table>
            </div>
        </div>
    );
};

export default NodeTable;

// codyze-console/src/main/webapp/src/lib/components/analysis/NodeTable.svelte
<script lang="ts">
  import type { FlattenedNode } from '$lib/flatten';
  import type { NodeJSON } from '$lib/types';

  interface Props {
    title: string;
    nodes: FlattenedNode[];
    highlightedNode: NodeJSON | null;
    nodeClick: (node: NodeJSON) => void;
  }

  let { title, nodes, highlightedNode = $bindable(), nodeClick }: Props = $props();
</script>

<div class="rounded bg-white p-6 shadow-md">
  <h2 class="mb-4 text-lg font-semibold">
    {title} ({nodes.length})
  </h2>
  <div class="overflow-x-auto">
    <table class="min-w-full divide-y divide-gray-200">
      <thead class="bg-gray-50">
        <tr>
          <th
            class="px-6 py-3 text-left text-xs font-medium tracking-wider text-gray-500 uppercase"
          >
            Type
          </th>
          <th
            class="px-6 py-3 text-left text-xs font-medium tracking-wider text-gray-500 uppercase"
          >
            Name
          </th>
          <th
            class="px-6 py-3 text-left text-xs font-medium tracking-wider text-gray-500 uppercase"
          >
            Location
          </th>
          <th
            class="px-6 py-3 text-left text-xs font-medium tracking-wider text-gray-500 uppercase"
          >
            Code
          </th>
        </tr>
      </thead>
      <tbody class="divide-y divide-gray-200 bg-white">
        {#each nodes as node (node.id)}
          <tr
            class={`${
              highlightedNode?.id === node.id ? 'bg-gray-100' : ''
            } cursor-pointer hover:bg-gray-50`}
            onmouseenter={() => (highlightedNode = node)}
            onmouseleave={() => (highlightedNode = null)}
            onclick={() => nodeClick(node)}
          >
            <td
              class="px-6 py-4 text-sm font-medium whitespace-nowrap text-gray-900"
              style:padding-left={`${node.depth * 10}px`}
            >
              {node.type}
            </td>
            <td class="px-6 py-4 text-sm whitespace-nowrap text-gray-500">
              {node.name}
            </td>
            <td class="px-6 py-4 text-sm whitespace-nowrap text-gray-500">
              L{node.startLine}:C{node.startColumn} - L{node.endLine}:C
              {node.endColumn}
            </td>
            <td class="max-w-xs truncate px-6 py-4 text-sm whitespace-nowrap text-gray-500">
              {node.code}
            </td>
          </tr>
        {/each}
      </tbody>
    </table>
  </div>
</div>
